name: Hello World Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello World!"
    - name: Print current date
      run: date
    - name: List directory content
      run: ls -l
