name: Simple Deployment Pipeeling

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Check style
      run: npm run eslint
    - name: Print Hello World
      run: echo "Hello World!"
    - name: Print current date
      run: date
    - name: List directory content
      run: ls -l
